### ISSUE TITLE
sync should not try to delete files that have never been synced.

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazidocs#4493]
Files that belong to entities that do not match the sync condition, are not synced.
When this files are deleted, the deletetion is "synced", this was producing an error fixed by https://github.com/huridocs/uwazi/pull/4492 because the file does not exist on the target, not a big issue since the error is fixed, but probably we do not want to sync deletions of not synced files ? 
Was this done on purpose because we do not know if the file was actually synced or not ? @fnocetti @RafaPolit

**Comment by RafaPolit** [comment]
I believe the answer is 'yes'.  Instead of keeping tags of what is synced and what not, we either:
- "sync and forget" if the document passes sync validation
- "delete without checking" if the document fails sync validation

I believe the same should apply to files.  Attempt to delete, whether the file exists or not.  Obviously, not failing if the file is missing.
