### ISSUE TITLE
Do a quick spike of Remix [2 days]

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazidocs#4499]
Remix: https://remix.run/
Use tailwind: https://tailwindcss.com/ for the styles

Render some entities from the library and be able to edit them.

- Developer experience
- Flexivility
- Does it adapt to our project?
- Server side rendering
- Testing

**Comment by Zasa-san** [comment]
During the spike we gather the following information, besides what can be found in the documentation and in relation to our use case:

- We would need to forgo our current state management practices since Remix uses a different paradigm. 
- The fundamental components are routes, testing these routes is exclusively done via E2E. Integration testing might require mocking certain aspects of Remix: https://github.com/remix-run/remix/discussions/2481
- Internationalization will require more in depth investigation to find a good solution to support dynamic translations pulled from the API.
- Remix resolves loading of route assets (with parallel loading like React Router 6) and error boundaries out of the box.
- Remix forms differ from the way we implement them now, but they are robust enough that we might not need supplementary libraries. 
- In general, Remix proposes a challenging change of mindset when developing.
- It’s quite simple to get up and running.

And about Tailwind: 

- Verbose, styling something might require a long string of keywords. 
- The philosophy behind it would collide with custom defined CSS, since the idea is that you don’t write CSS rules, but use the ones provided by Tailwind.
- In general, it’s quite nice.
- There are extensions to manage Tailwind’s class name composition in VSCode.
