### ISSUE TITLE
Text field character limits

### ISSUE THREAD

**Issue by serena-huridocs** [huridocs/uwazidocs#4520]
Our partner has recently reported an issue. Essentially, their issue was that they were unable to save the edited version of an entity. During our meeting, one of the users shared her screen, and I made sure that she was not able to save the edited version of an entity even after she clicked the save button several times. The system did not throw any errors at that moment.

The user says that it had already happened a few times. The page was simply ‘blinking’ and refusing to save the changes.

The user was editing the information in the rich text property during our meeting. So when our meeting finished, I was asked what the text field character limit is. The user mentioned that she was trying to add 25 thousand characters to that rich text field.

I tested the rich text property myself to see what the text field character limit is. After doing it several times, I figured that the instance did not allow me to add texts, exceeding 17 thousand characters (the texts were in the Cyrillic script). So I spotted the same issue: there was no information/errors, regarding the problem with the rich text property, I just did not manage to save the edited entity.

Additionally, the partner actively uses the submission forms in order to import their information to the database and they already informed us about other difficulties working with the forms. Multiple users say, they were unable to submit the information through the form, and the most confusing part was that the system did not inform them why it was throwing those errors. The notifications that they have noticed only said: ‘An error has occurred'. I assume that this could happen because they also tried to add 25 thousand characters to the text fields through submission forms. But the system has never informed them about the current text character limits.

**Comment by nwyu** [comment]
Currently there seems to be a 17,969 character limit on Uwazi's rich text field.

- Users are unable to save the entity if they exceed this number of characters.
- And there is no feedback to the user which indicates that they have reached the cap.

**Comment by txau** [comment]
This could be related to a missconfiguration on our mappings when trying to use long texts as a terms index. It could be easily fixed from our elastic mappings. cc @fnocetti

**Comment by fnocetti** [comment]
@txau I don't think it's related to a mapping error. Also, I was able to save more than 32000 characters in a rich text in a local deployment. 
I think this is related to a Lucene limit on the field content size.
In order to prevent Lucene from failing, we enforced the limit in a validator here: https://github.com/huridocs/uwazi/blob/c054a8764d08cd4cab6af609895db9c05e58ba1c/app/api/entities/validation/metadataValidators.js#L74

In my local tests, the server is returning a validation error message but the client is not handling it in anyway, so it just looks like the button is doing nothing.

If I'm correct, then the only option left is improve the UI feedback and show a proper message in the UI. For that, we should assign to the front end team.

**Comment by txau** [comment]
@fnocetti got it. At the same time we are mapping in different ways the long texts from the PDFs and the rich text fields content. Maybe that should not be the case? here they explain the 32KB limitation is for terms: https://github.com/Graylog2/graylog2-server/issues/873

**Comment by fnocetti** [comment]
I tried increasing the validator limit to ~132k and elastic is not failing to me. I might be missing something from the original issue (because of which we put the validator in place).
That said, it makes sense that if we can store the text from a PDF, we should be able to store the text from a field. The difference I see between both of them is that for fields we are using `tokenizer` as analyzer, while using `standard` for the fulltext. I still don't know how using a standard analyzer bypasses the lucene limits.
That will need further research.

**Comment by txau** [comment]
@fnocetti just an educated guess: because we don't use *terms* indexing for the PDF text, but we use the same mapping for long and short text. So Elastic is complaining about having terms that exceed the 32kb length.

**Comment by fnocetti** [comment]
The research result shows that the current ElasticSearch mapping for rich text fields is the appropriate to allow unlimited text length and the validation limiting the length of the values is either obsolete (from a previous mapping configuration) or a mistake. The decided solution is to remove the validation for this field type.
A PR is already in progress.
