### ISSUE TITLE
Public forms have their own size limits, increase them to match other areas or remove them

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#4577]
Public Forms should adhere to the normal size limits of our application.  Apparently they currently have a more limiting size.  Either remove them or make them match.

---------------

Also this is being triggered on public forms a lot. Public forms have their own limits, check this out and create a separate issue if needed.

_Originally posted by @txau in https://github.com/huridocs/uwazi/issues/4450#issuecomment-1111218305_

**Comment by txau** [comment]
This may me affecting remote public form more than other forms.

**Comment by fnocetti** [comment]
@RafaPolit @txau what size is this issue referring to? Is it attachments size?

**Comment by txau** [comment]
@fnocetti it is unclear, it may be the whole form, in fact this line: `app.use(/\/((?!remotepublic).)*/, bodyParser.json({ limit: '1mb' }));
`

**Comment by LaszloKecskes** [comment]
@txau @RafaPolit Can you supply an example, where this fails? 

The way I currently understand it, we have limits on the remotepublic api in the line @txau supplied, and inside the api definition. The second one is 20MB. Both of these limits apply to the request body. However, after a little research, it seems that express uses the same json parser to parse the body (the `bodyParser` there), with the default settings, which is (according to their npm page) is 100KB. Therefore, unless I'm missing a setting somewhere, these endpoints actually seem to have a larger limit, than our other api endpoints. So, it would be helpful to see an example, whether there is something extra I'm not considering.

**Comment by txau** [comment]
@LaszloKecskes is the 100kb limit of bodyParser affecting the remotepublic API?

**Comment by LaszloKecskes** [comment]
> @LaszloKecskes is the 100kb limit of bodyParser affecting the remotepublic API?

That is my current guess (just with 1MB, not 100kB), since the error in the linked issue (#4450) is an error from the body-parser package ([see "request entity too large" here](https://github.com/expressjs/body-parser)). However, the line you have linked sets the limit for this endpoint to 1MB, which is larger than the default 100kB, so it should be able to take more, than our other endpoints (i.e. if you cannot send an entity via the remotepublic api, you should not be able to save it through the normal entity save flow either). 

However, I have not been able to replicate this, since I have not been able to manually create a large enough entity to actually trigger this, since this is a lot of text, and you reach the rich text field limit way before you hit the 100kB (10 rich text field almost filled was only 9-10kB). Do we have an actual example or steps to reproduce? If not, I could try to generate a json that breaks this and send it to the api directly, but even if we do that, and we fix it, I will not be able to confirm that that is the actual error you are seeing.

**Comment by txau** [comment]
@LaszloKecskes could it be that the limit is reached not due to text input but because of attached files?

**Comment by LaszloKecskes** [comment]
I've tried to attach some ~1.5MB pdfs (multiple to the same), and it did not break anything. I'll try with bigger to see what happens, but at the moment, I think the linked error message is about the request body. Can you share other error messages we see, if any?

**Comment by txau** [comment]
@LaszloKecskes this is how it looks like in the error log. Since it is coming from a public form, we don't really now what the content was.

```
url: /api/remotepublic
PayloadTooLargeError: request entity too large
    at readStream (/opt/uwazi/cores/core-1.60.3/node_modules/express-http-proxy/node_modules/raw-body/index.js:155:17)
    at executor (/opt/uwazi/cores/core-1.60.3/node_modules/express-http-proxy/node_modules/raw-body/index.js:112:5)
    at new Promise (<anonymous>)
    at getRawBody (/opt/uwazi/cores/core-1.60.3/node_modules/express-http-proxy/node_modules/raw-body/index.js:111:10)
    at maybeParseBody (/opt/uwazi/cores/core-1.60.3/node_modules/express-http-proxy/lib/requestOptions.js:96:14)
    at Object.bodyContent (/opt/uwazi/cores/core-1.60.3/node_modules/express-http-proxy/lib/requestOptions.js:104:12)
    at buildProxyReq (/opt/uwazi/cores/core-1.60.3/node_modules/express-http-proxy/app/steps/buildProxyReq.js:12:84)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
original error: {
 "message": "request entity too large",
 "expected": 83626726,
 "length": 83626726,
 "limit": 20971520,
 "type": "entity.too.large"
}
```

**Comment by txau** [comment]
I also found this other error that may be related:
```
Error: Payload Too Large
    at Request.callback (/opt/uwazi/cores/core-1.58.1/node_modules/superagent/src/node/index.js:879:15)
    at IncomingMessage.<anonymous> (/opt/uwazi/cores/core-1.58.1/node_modules/superagent/src/node/index.js:1130:18)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**Comment by LaszloKecskes** [comment]
This was helpful. From the first one I can see that it is probably triggering the check not for the body-parser, but the one when it tries to pass it over to the other instances public form. Which, indeed, might be a file after all. Thanks!

**Comment by LaszloKecskes** [comment]
Confirmation: the api/remotepublic 20MB limit counts the files.

**Comment by txau** [comment]
@LaszloKecskes I think we need to increase the limit, some people are trying to send video files that can have hundreds of MB. So if anything, the size restrictions should be controlled by the load balancer and Uwazi should have a big default. I'd say 500MB.

**Comment by LaszloKecskes** [comment]
Here's the pr:
https://github.com/huridocs/uwazi/pull/4636

@txau, would you like to do some functional testing, or should I just merge it?

**Comment by txau** [comment]
@LaszloKecskes is this fix for public form alone? or will it also increase the limit for regular uwazi forms and uploads?

**Comment by LaszloKecskes** [comment]
After a call, change of scope in the issue: make sure that every file upload "path" in Uwazi can take a 500MB file.

**Comment by LaszloKecskes** [comment]
@txau I have performed the following. The cases without comment went through.

Test files: 
- avi: same short video concatenated 9 times to make a file that measures as 476,3 MB in Linux UI - 454,27MB in Uwazi
- pdf: same image concatenated ~274 times to make a file that measures as 498,5 MB in Linux UI - 475,45MB in Uwazi

Test paths:
- edit existing entity:
add as media file (avi) - Promised type was not provided error
add as primary document (pdf)
add as supporting file (both)
- entity creation:
add as media file (avi) - Promised type was not provided error
add as supporting file (both) - Promised type was not provided error
- direct public form:
as media (avi)
as document (pdf)
as attachment (both)
- remote public form:
as media (avi)
as document (pdf)
as attachment (both)

At the marked errors (all of the same type) it is not immediately clear to me what is wrong. It looks like a bug, rather than an explicit size limit, but smaller files still work, so size might be a factor after all. Those cases would take more time to debug. I would recommend to merge the current pr, as it raises the remote public form size limit, so the users can use it, and debug the faulty cases in a separate issue (or this issue, but second pr).

**Comment by txau** [comment]
@LaszloKecskes it makes sense, let's do that.
