### ISSUE TITLE
IX - Modifiying entities on PDF sidepanel

### ISSUE THREAD

**Issue by Zasa-san** [huridocs/uwazidocs#4651]
On instances with more than one language the flow for modifying entities via the PDF sidepanel can be really confusing.

In an instance with 2 languages (e.g. Spanish and English):
- Create entities with documents in Spanish.
- Generate suggestions for those documents.
- Visit the suggestions panel for a property while having the UI in English.
- Modify a value for an entity with the PDF sidepanel, save.
- Reload.

After the reload, the value on the table will go back to whatever was before the modification, since the change was done on the English entity, but the table is displaying data from the Spanish one.

**Comment by grafitto** [comment]
@konzz and I have gone through the bug, we found out that the problem is we a retrieving the entities in the language of the suggestions instead of the language of the UI, but when you edit on the PDF side panel, the edit happens on the language of the UI (which is what is expected). 

Possible solution would be to retrieve the entities in the language of the UI, that way when you edit it via the PDF sidepanel, the changes match with the table.

However we think because the backend team is already working on a major refactor of how the suggestion states are retrieved, it makes sense for this change to be made during the refactor.

**Comment by txau** [comment]
@grafitto 

> the edit happens on the language of the UI (which is what is expected).

That is not correct. We want to avoid a bad pattern from the past where the users can't work on metadata that is not the same as the current UI language. In other words, the side panel needs to save the value in the language of the suggestion. 

It can happen that the language of the suggestion does not exist as UI configured language, in which case it should be applied to the current UI language. I think we should add a UI hint for users to understand to which language the suggestion will be stored to.

**Comment by grafitto** [comment]
@txau we have been able to use the entity which language match the suggestion language, however, there is an issue when the language is not configured, your suggestion is we use the UI language. In the current implementation where the state is calculated on the fly, it is easy to know the UI language via `Content-Language` header. However, in the implementation @LaszloKecskes is working on, the state is pre-calculated therefore in some cases its not possible to know the language of the UI because redis messages can not access UI language. In that case we think using the `defaultLanguage` would be the more appropriate fallback.


Also, what happens if the user has a suggestion of a language that is not configured, then the user configures that language?

**Comment by txau** [comment]
@grafitto I see. So when the language is not configured we should also use the default language.
