### ISSUE TITLE
A way to present repeated inherited values in a consolidated format (5 pts)

### ISSUE THREAD

**Issue by llfinch** [huridocs/uwazidocs#4706]
I've got a partner collection that has two main types of entities: Documents and Paragraphs. We need to be able to filter Documents by topic, but this information currently lives on the Paragraph entities. Any easy enough solution is to add a relationship property to the Document and configure it to inherit the topic information from the Paragraph entities. 

BUT in this particular collection, there could be 50+ Paragraph entities that are associated with a Document entity and there is always a lot of overlap among the topics on each Paragraph entity. As a result, this creates a problem: when viewing the entity, a user is going to be confronted with an absurdly long list of individual inherited values repeating over and over again - doing harm to the meaningfulness of the information. A small example: 

![image](https://user-images.githubusercontent.com/56080527/171843093-7e94caef-e96a-451e-800c-5af102b04b12.png)

We need a way to be able to present this information in a consolidated format in order to make the information here meaningful and not drown users in a sea of repeated values (not dissimilar to how filters are presented in the Library sidebar, like below).

![image](https://user-images.githubusercontent.com/56080527/171843190-ab7810c2-7772-4d30-a452-5cf0f1ba6d0a.png)

**Comment by txau** [comment]
@llfinch thanks for reporting this. It tackles an interesting problem and while I still don't have  a proposal of a solution, I have some ideas I wanted to document for the upcoming discussion.

Redundant information can happen due to similar scenarios:
- Inheriting properties that can have the same values
- Inheriting several times the same value (ie. creating more than one relationship to the same entity)

Note that this cannot happen on thesaurus based select or multi-select because we don't allow duplicated values in the thesaurus and our UI forces the users to only pick-up each value at most one time. So this is a problem affecting relationships alone.

Solutions:
- Display redundant values (as it is happening at the moment) which may be undesirable in many cases
- Aggregate the values, displaying the value once but indicating the amount of repetitions
- Disambiguate the values, by adding extra information such as which entity it is coming from

The best solution may depend on the context and maybe we need to offer several options with good/safe defaults. This could be an inherited field configuration plus a UI option for the end user to switch between views.

cc @RafaPolit @fnocetti @daneryl

**Comment by RafaPolit** [comment]
The disambiguation is a more "ambitious" approach which is already been developed as part of #4232 .

For now, I think we can do a client-side parsing of data to do the second bullet: aggregate the identical results so that we don't lose the extra information.  It would read:

Document Topics
- Governance (3)
- Violence
- Movement (2)
