### ISSUE TITLE
IX: leftover obsolete suggestions

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#4876]
**Describe the bug**
After training and processing all the new suggestions, there is always a bunch of remaining suggestions with the status "Obsolete". They are always less than 50, so I suspect the latest batch is not being processed.

**To Reproduce**
1. Train the model and wait for all the suggestions to be processed
2. Filter by obsolete. At this point the list should be empty.

**Expected behavior**
All suggestions are actually processed.

**Comment by txau** [comment]
@LaszloKecskes this may be the culprit:

![image](https://user-images.githubusercontent.com/489831/179854960-324c480f-7b64-4b53-be7b-4f442255da1a.png)

As you can see, this entity has 2 main documents, one of them having no language defined. I checked a few other examples and they all show this problem.

Main documents should always have a language. When the language is unknown or not supported the value should be "Other".

My hunch is that we do not need to fix anything in the machine learning module but run a migration/fix for documents without language.

**Comment by txau** [comment]
More over, some other documents are also giving problems:

![image](https://user-images.githubusercontent.com/489831/179864935-a163233f-b88f-4494-a825-9c16d939a002.png)

**Comment by txau** [comment]
Further inspection of more documents revealed some of the leftover documents don't have any apparent errors or missing language. There may be a problem with the PDF format when we attempt to process it on the information extraction end as this end-point uses different PDF parsing libraries than Uwazi.

**Comment by LaszloKecskes** [comment]
Today I've tried the following:
- re-run the country text property on the server, to see if it is consistent. It is, the same suggestions got stuck again.
- download the dump
- re-run locally with the full set, locally I also get the same obsoletes
- after pruning back the data to contain only these entities (which results in 36 entities and 25 suggestions, instead of 13, due to language and file availability), re running it with batch size of 5 gives just 4 stuck in obsolete
- re-running the pruned set with the original batch size of 50 gives 3 stuck in obsolete. In these cases due to the low number I can see that these do not even get sent (the redis log of the server shows that it is only processing 21 and 22 suggestions, respectively)

This is still very confusing, as it seems to be deterministic (i.e. always the same things hang up), but batch size seems to be a factor, so it is not only local data errors. On the other hand, during a different issue I've got an obsolete because of data errors (it was a trivial missing segmentation in that case), so some of these might still be data errors. Nevertheless, at least now I have a local failing example to try to debug.

**Comment by LaszloKecskes** [comment]
I think we've got it. We were on track yesterday, the culprit seems to be that "other-way-around" style filtering in the beginning:
```
  const [currentModel] = await ixmodels.get({ propertyName: property });

  const suggestions = await IXSuggestionsModel.get(
    { propertyName: property, date: { $gt: currentModel.creationDate } },
    'entityId'
  );

  const suggestionsIds = suggestions.filter(x => x.entityId).map(x => x.entityId);

  const entities = await entitiesModel.getUnrestricted(
    { template: { $in: templates }, sharedId: { $nin: suggestionsIds } },
    'sharedId'
  );
```

This gets the sharedIds that are connected to already processed ("time greater than model creation date") suggestions, than gets the entities that are _not_ connected to them. However, a sharedId represents multiple entities: if there are entities with files in multiple languages, processing one will cover this filter and it will not find later the other ones. The errors we see are when a group of entities are broken up by the batch limit.

As a funny side note, this might also explain your observation about how the number of remaining obsoletes was close to the total number of suggestions / batch size. The batch size is 50, and the db has three languages. 51 is the number divisible by three, so assuming a uniform, complete coverage of languages with documents, and entities subsequently in one groups, we loose one per batch. However, that assumption is probably not entirely true, so in this specific case if was probably still a coincidence.

Re-implementing those queries in the simple direction (get unprocessed -> get files directly through the ids, no sidetrack to entities) results in a clean run locally on the ~600 count country_text example. I'll try to have a pr and deployment ready tomorrow, so we can see it on the server as well.
