### ISSUE TITLE
User permissions table not completely translatable

### ISSUE THREAD

**Issue by llfinch** [huridocs/uwazidocs#4894]
**Describe the bug**
In `Settings --> Users` on the tooltip next to `Role`, there is a table that breaks down the specific powers that a user has according to the role they have (collaborator, editor, admin). Unfortunately, it appears that only a select few parts of this table is translatable: 

Translatable (because the term is included in `Settings --> Translations --> User Interface`):
- Permission
- Collaborator 
- Editor
- Admin
- Create connections and references
- Manage site settings and configuration
- Add/delete users and assign roles
- Configure filters
- Add/edit translations
- Legend
- Permission on entities explicitly shared with the user
- Close

Not translatable: 
- Create new entities and upload documents
- Create table of contents
- View entities
- Edit metadata of entities
- Delete entities and documents
- Share edit access with other users
- Share entities with the public
- Configure templates
- Create and edit thesauri
- Create connection types

Furthermore, the use of "connection" is obsolete and should be replaced with "relationship", so:
- "Create connections and references" --> "Create relationships and references"
- "Create connection types" --> "Create relationship types"

**Expected behavior**
I would expect to be able to fully localize this table, especially something as basic to the functioning of Uwazi as the explanation of permissions related to user roles.

**Screenshots**
(Any term with "!!!" appended to it means that it is indeed translatable via `Settings --> Translations --> User Interface`)
![imagen](https://user-images.githubusercontent.com/56080527/179210272-075d6ae8-28ce-4aad-b592-eb92e2060ba8.png)

**Comment by Zasa-san** [comment]
The missing translations can be added in a simple way. 

For the part about migrating existing erroneous keys:
I'm looking into updating the keys so it's consistent with the new way of naming connections, and users don't end up with a weird reference to connections in the translation UI and csv files. 
In the cases where the user has translated these keys into other languages the translation wont change, only the key. The UI will only reflect this update of terms in English, and not modify existing translations in other languages.

**Comment by Zasa-san** [comment]
@llfinch These new keys and values will be added after this issue is closed.
```
key,English
"Create new entities and upload documents","Create new entities and upload documents"
"Create table of contents","Create table of contents"
"View entities","View entities"
"Edit metadata of entities","Edit metadata of entities"
"Delete entities and documents","Delete entities and documents"
"Share edit access with other users","Share edit access with other users"
"Share entities with the public","Share entities with the public"
"Configure templates","Configure templates"
"Create and edit thesauri","Create and edit thesauri"
"Create relationship types","Create relationship types"
```

The following keys will change, so translations CSV should be updated:
| Old keys                                                       | New keys                                                     |
|-----------------------------------------------------------|-------------------------------------------------------------|
| Create connections and references                         | Create relationships and references                         |
| Add connection                                            | Add relationship                                            |
| Confirm delete connection type:                           | Confirm delete relationship type:                           |
| Are you sure you want to delete this connection type?     | Are you sure you want to delete this relationship type?     |
| Cannot delete connection type:                            | Cannot delete relationship type:                            |
| This connection type is being used and cannot be deleted. | This relationship type is being used and cannot be deleted. |
| connections | relationships |
|Changing the type will erase all connections to this entity.|Changing the type will erase all relationships to this entity.|

This will not affect existing translations.
