### ISSUE TITLE
Exclude non related entities from the default filter  

### ISSUE THREAD

**Issue by agsabbagh** [huridocs/uwazidocs#5033]
I've a property which is mutual between 4 templates,  I have defined this property as a default filter, but in the library main page this "default filter" consider the non related entities from the other templates as "no-label" entities however the property is not a part of those templates, is there a way to exclude those non related templates from the default filter ? 

![image](https://user-images.githubusercontent.com/66379177/186409386-22c9ac05-b979-4bd9-81e4-adf3a4f82f60.png)

**Comment by txau** [comment]
@agsabbagh I have been able to replicated the issue locally. This is a bug on our end and requires fixing. 

From my tests this problem is affecting properties of the types select, multi-select and relationship when configured as default filter. As explained by @agsabbagh it is aggregating all entities under the "No label" option even when they don't have said property, when the filter is acting as a default filter.

**Comment by txau** [comment]
@agsabbagh thanks for reporting. We'll release a fix soon.

**Comment by RafaPolit** [comment]
Since this aggregation could be inferred as both: "entities that COULD have that property but don't", but also "entities that don't have that property at all", we have talked and the least "ambiguous" solution is to actually not show the "no label" aggregation when it is part of the default filter.

If the user wants to actually see the "no label" aggregation for a particular template or group of templates, they would need to actually select those templates from the top of the filters sidepanel.
