### ISSUE TITLE
Error in table view demo

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#5075]
**Describe the bug**
Error in table view demo.

![image](https://user-images.githubusercontent.com/489831/188182079-9d56f812-ed8d-42c4-b56c-ced8b97af794.png)

**Comment by Zasa-san** [comment]
This error is triggered when trying to parse markdown fields. The entities that trigger this error have markdown fields that are empty arrays. Usually we should find:
```
[
  { value: “” }
]
```
or the property not present on the entity. But for these entities the property is `[]`. Since `app/react/Markdown/markdownToReact.js` is calling the `replace` function on the property, it will throw an error when the empty array value reaches it.

This is not affecting the card view since these empty arrays have been filtered in `app/react/Metadata/components/Metadata.js` before.

**Comment by Zasa-san** [comment]
It's likely that these entities with empty arrays as properties are legacy and exist on development since the database gets reset. New entities and instances should not have this problem.
