### ISSUE TITLE
CSS problem

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#5292]
![image](https://user-images.githubusercontent.com/489831/200617297-c8e63fd3-3c39-4bff-acc7-89a0f92483ce.png)

**Comment by RafaPolit** [comment]
Making the background transparent should fix it.  But the height of the element should be the entire height of the header.

**Comment by Zasa-san** [comment]
The issue was hare:
https://github.com/huridocs/uwazi/blob/f361499d382a684718be4ec0e1af64eb13494ac7/app/react/App/scss/layout/_header.scss#L290-L295

As a rule of thumb never define background color unless you need to intentionally set it. If a element need to have a default background color removed, like in the case of buttons, use `unset` or `transparent`.
