### ISSUE TITLE
Disappeared "Edit" (action) buttons in relationships screen for Document View flow

### ISSUE THREAD

**Issue by salvalacruz** [huridocs/uwazidocs#5438]
**Describe the bug**
When viewing an entity and accessing the relationship screen, the "Edit" button is no longer available. 
This happens in some circumstances or instances (not identified why), but the "Edit" button remains available in other instances.

**To Reproduce**
1. Select an entity (with previoulsy created relationships with other entities).
2. Click on 'Relationships' button
![image](https://user-images.githubusercontent.com/73410334/212333285-93afd7b0-b649-4422-b884-2d16a11a4574.png)
3. Scroll down to the bottom left of the screen.
4. See if it the 'Edit' button is shown or not.

**Expected behavior**
If the viewed entity has relationships already created, the 'Edit' button should be available in the Relationships screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/73410334/212331923-65b58a72-a0a4-4294-8433-e1e84dd8a3e2.png)

**Device (please select all that apply)**
 - [X] Desktop
 - [ ] Mobile

**Browser**
Tested with Chrome and Brave.

**Additional context**
The problem comes from a specifc instance.

**Comment by RafaPolit** [comment]
The KEY process here is: this is happening only on Document View.

So, the buttons are shown as expected on the entity view -> relationships view, but they are MISSING on document view -> relationships view.

This is because the edit buttons on the document viewer are found on the sidepanel, so somehow they are missing when you change into relationships view from the main document view.  We need to bring them back.

**Comment by Zasa-san** [comment]
This was caused by a mishap when upgrading the action buttons. In `app/react/Viewer/components/Viewer.js` the component was checking for the `connections` tab which has been renamed to `relationships`. There was no test to cover showing this buttons when switching from the document view to the relationships view.
