### ISSUE TITLE
Numeric fields are not properly validated in post api/entities

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazidocs#5469]
**Describe the bug**
If you send a string value on a metadata property that is configured as numeric, the endpoint will not give a validation error and save the string in the DB.

**To Reproduce**
1. Configure a template with a numeric value
2. Use curl or other tool to save an entity with the numeric property filled with a string
3. A string is now saved on a property that should be a number

**Comment by fnocetti** [comment]
This is only reproducible if the value is the string representation of a number. e.g `"30"` instead of `30`.
There's an explicit validation allowing string representation for numbers in numeric fields, but then the value is not transformed accordingly. I think there's no reason to allow string representations, even exponential notation is allowed without it.
Do you agree? @RafaPolit @txau

**Comment by fnocetti** [comment]
We decided to allow string formatted numbers to keep the backwards compatibility.
