### ISSUE TITLE
e2e visual regression suites have flaky tests

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazidocs#5470]
this are the tests that are failing lately
 - "should display relationships on the sidepanel"
 - "should display Bar chart graph in page"

**Comment by txau** [comment]
Is this flakiness happening in the CI environment or local? We know visual regression is very prone to diffs depending on the environment. I strongly believe they should be always run on virtual machines/docker with a fixed spec. We should then make sure we maintain the virtualization so it is uniform for everyone.

**Comment by RafaPolit** [comment]
This flakiness is mostly in CI

**Comment by txau** [comment]
@RafaPolit are we managing stack versioning in CI. If this is being rendered son chrome or firefox but we don't have a fixed version it could happen that the rendering changes between versions?

On the other hand, if we set a fixed version, we may miss the chance of picking up problems with newer versions of the browser.

**Comment by daneryl** [comment]
After debugging this

> "should display relationships on the sidepanel"

I believe the flakiness comes from uwazi (new sidepanel relationships view), not the tests, sometimes the side panel do not render the relationships, do not know why and im not able to replicate consistently.

**Comment by konzz** [comment]
The problem of entities not being rendered happens because Uwazzi sometimes request the references with an empty sharedid.

This action is the one that does the call:
https://github.com/huridocs/uwazi/blob/4baf97e0668be168b08a6b83225879292738dd46/app/react/ConnectionsList/actions/actions.js#L9-L10

It receives the `requestParams` from this other one:
https://github.com/huridocs/uwazi/blob/4baf97e0668be168b08a6b83225879292738dd46/app/react/ConnectionsList/actions/actions.js#L23-L26

as you can see, the params come from the redux store (`getState().relationships.list`)

this action is called by multiple actions, but in this scenario this one is calling it:
https://github.com/huridocs/uwazi/blob/4baf97e0668be168b08a6b83225879292738dd46/app/react/ConnectionsList/actions/actions.js#L31-L61

right at the end it calls `return searchReferences()(dispatch, getState);` but inside of another API call, if you look at the code this function does not set the sharedId in the store at any point.

In this whole process the function that actually sets the sharedId in the store that the search function uses and sometimes is set and sometimes is not is this one (in a different file library actions): `dispatch(actions.set('relationships/list/sharedId', sharedId)); `

https://github.com/huridocs/uwazi/blob/4baf97e0668be168b08a6b83225879292738dd46/app/react/Library/actions/libraryActions.js#L383-L391

but only sets the sharedId AFTER the api call, so the setter, and the need for it both happen asynchronously, and the [DocumentSidePanel](https://github.com/huridocs/uwazi/blob/development/app/react/Documents/components/DocumentSidePanel.js) does not WAIT for this functions to end, calls them both at the same time:

https://github.com/huridocs/uwazi/blob/4baf97e0668be168b08a6b83225879292738dd46/app/react/Documents/components/DocumentSidePanel.js#L78-L83
