### ISSUE TITLE
Create Line Chart

### ISSUE THREAD

**Issue by petkong** [huridocs/uwazidocs#5545]
What is the code to create line chart?

**Comment by RafaPolit** [comment]
There is no "automated" abstraction to create line charts at this time.  We only wrap a few chart types that can be used "out of the box" at this point.  There have been discussions to expose the entire `recharts` library to the page design, but is not as straightforward.

The reason we have not done this as a higher priority feature it that with a page's script + html, you could import any chart library you need, and present the data in the very particular need of your collection.

Still, there are some obvious advantages of having this simplified.  Could you elaborate on your specific needs at this point?  Is it purely cosmetic?  Why does the barchart not fulfill your needs? 

Thanks for any added info.

**Comment by petkong** [comment]
Ok Rafa. Thank you for rthe information. I still test it using Barchart as you can see on the link >>> https://kebebasanberkesenian.uwazi.io/page/30u7yrphus9/statistik

Is it possible to justified the text automatically follow the width of the bar chart. Because for descriptions with long text it is not visible on the bar chart.

**Comment by RafaPolit** [comment]
I see the problem of that layout.  Yes.  This will probably not be solved with a line-chart either.

We have encountered this problem before and we have a possible solution, which is unfortunately not documented in the documentation, but it has been implemented for quite a while.

There is a way to define a `shortLabels` property in the `<BarChart>` component, which allows to define "shorter labels" when property names are longer.  Maybe this is enough for your current needs?

So, for example, the `Jenis Pelaku` barchart could be defined like this:
```
Jenis Pelaku
<Dataset />
	<BarChart property="tipe_pelaku"
	content="63b3f1ce91bb2a536afc0c7b"
	colors="337084, #00878b, #009b76, #5ba94d, #aaaf15, #ffa600"
        shortLabels='{"Entitas pemerintah": "Pemerintah", "Entitas non-pemerintah": "Non-pemerintah", "Individu/kelompok dalam posisi yang memiliki kekuasaan.": "XYZ"}' />
```

Try it out, and see if this helps mitigate the problem.  Obviously, `XYZ` needs to be replaced with something semantic.   This would need to be done with all charts that are susceptible to this problem.

On a side note, I believe there is a misconception of the `<Dataset />` component.  You only require multiple Datasets if you are going to perform different queries than the "default" query, and, in that case, they should be named.  In your particular scenario, it's enough if the first line reads `<Dataset />` and then you just insert each BarChart.  Furthermore, the `content` property is not a valid property for the component and it has no effect on the component.  So you are safe removing it from the Barchart.

```
Jenis Pelaku
<BarChart
  property="tipe_pelaku"
  colors="337084, #00878b, #009b76, #5ba94d, #aaaf15, #ffa600"
  shortLabels='{"Entitas pemerintah": "Pemerintah", "Entitas non-pemerintah": "Non-pemerintah", "Individu/kelompok dalam posisi yang memiliki kekuasaan.": "XYZ"}'
/>
```

There is no need to "repeat" the Dataset, it is already available for the entire page just by calling it once at the beginning of the page.

I can only assume that the "content" property was meant to be the "context" property, which would be required in order to know with which context to translate the property names.  In this case, that would be the template ID which holds the property, but I don't see that those "content" values match any templates.  Where did this values come from?

Hope this helps, let me know if this is not enough for your needs.

Best regards,
Rafa.

**Comment by RafaPolit** [comment]
Other alternatives include:
- modifying the font size of the labels
- using vertical layout on the Barchart

I have prepared this page with those scenarios so you can see a broader scope of options:
```
<Dataset />
<style>
text.recharts-text.recharts-cartesian-axis-tick-value {
    font-size: 13px;
}
</style>

Bidang Seni
<BarChart
  property="bidang_seni"
  colors="337084, #00878b, #009b76, #5ba94d, #aaaf15, #ffa600"
/>

Jenis Pelaku
<BarChart
  property="tipe_pelaku"
  colors="337084, #00878b, #009b76, #5ba94d, #aaaf15, #ffa600"
  shortLabels='{"Entitas pemerintah": "Pemerintah", "Entitas non-pemerintah": "Non-pemerintah", "Individu/kelompok dalam posisi yang memiliki kekuasaan.": "XYZ"}'
/>

Karakteristik Korban
<BarChart
  property="karakteristik_korban"
  layout="vertical"
  colors="337084, #00878b, #009b76, #5ba94d, #aaaf15, #ffa600"
/>
```

As you can see, the Karakteristik Korban chart which has been changed to layout vertical now shows all the lengthy text even taking up to 3 lines.

**Comment by RafaPolit** [comment]
And a final note, the first color definition is missing the `#` symbol, and that is what it is rendering black, so you should add the symbol to the colors property:
`colors="#337084, #00878b, #009b76, #5ba94d, #aaaf15, #ffa600"`

This renders the nice blue tint originally intended.

**Comment by petkong** [comment]
Dear Rafa,

Thank you so much your best support. Your code works fine as you can see on : https://kebebasanberkesenian.uwazi.io/page/8jxjnv24io6/statistik-2-css

One more thing regarding Barchart. How do I add the total cases besides the Barchart with a large circle along with generating numbers automatically from aggregate data like the Bar Chart example (Court case per state) on the example website https://cleen.uwazi.io/

The next question are:

1) How do I make an automatic number aggregate like on the website: https://cleen.uwazi.io/
  which displays 4 large circles with automatic links to their aggregated data.
2) Displays a Pie Chart along with its supporting data and automatic links to aggregate data such as the example website: https://cleen.uwazi.io/

I put the draft design at the following address : https://kebebasanberkesenian.uwazi.io/page/8gxeigacd83/pie-chart

Thank you so much for everything.

Best regards,

Andri

**Comment by RafaPolit** [comment]
I'm glad the code worked as expected.

Creating pages like the one on the Cleen collection requires combining some interactive components like the BarChart, but mostly HTML + CSS design where values and links are taken from creating queries to the Database.

I can give you small pointers, but creating such pages usually requires time from someone proficient in web page design and a bit of scripting in order to get them to work like that.

Your starting point should be the documentation for those interactive components:
- https://uwazi.readthedocs.io/en/latest/admin-docs/analysing-and-visualising-your-collection.html

Here you will get an overview of the different components you may have access to.

For example, the counter with the aggregation on the side of the BarChart is not a "feature" of the BarChart, it is a different HTML DIV positioned side by side with the Barchart.  The value is rendered with a `<Counter ... />` component as described in the link above.  The actual "circle" is normal CSS styling applied to the counter's containing element.  The link below is a regular `<a ...>Link</a>` element pointing to a particular query on the collection to filter those results.

The legend next to the Pie is yet another similar scenario: you are seeing an HTML structure of 4 columns, the leftmost column contains a Pie just like the one you have rendered, the second column uses a `<ListChart ... />` component pointing to the same property which will render the values and the labels as plain text.  They are made into nice circles and text via regular CSS.

As mentioned, what appears to be "extensions" of the same functionality are just simply different elements stitched together with regular HTML and CSS programming.  Feel free to play around with the different options and see what you come up with.  We know that the documentation is not really comprehensive and there may be 'hidden' features that are not documented (like the ones pointed out in previous posts) and we will be happy to help with those.

We do have in-house people dedicated to this, let me know if you want your PM to get in touch with you so we can see if that is a better option for you.

Best regards,
Rafa.

**Comment by petkong** [comment]
Dear Rafa,

Thank you so much for the explanation. I will explore more. Regarding the template I still have some issues :

Some of the data cannot be displayed in chart form:

**Template Korban**
- Unit Korban
- Status korban


**Template Pelaku**
- Status Pelaku


**Template Peristiwa**
- Lokasi Kejadian

When I check the API template >> https://kebebasanberkesenian.uwazi.io/api/templates

Only generate the id number but the content number didn't show up.

Best regards,
Andri

**Comment by RafaPolit** [comment]
For me, this works:
```
<Dataset />

Unit Korban
<BarChart
  property="unit_korban"
  colors="#337084, #00878b, #009b76, #5ba94d, #aaaf15, #ffa600"
/>

Status Korban
<BarChart
  property="status_korban"
  colors="#337084, #00878b, #009b76, #5ba94d, #aaaf15, #ffa600"
/>

Status Pelaku
<BarChart
  property="status_pelaku"
  colors="#337084, #00878b, #009b76, #5ba94d, #aaaf15, #ffa600"
/>

Lokasi Kejadian
<BarChart
  property="lokasi_kejadian"
  colors="#337084, #00878b, #009b76, #5ba94d, #aaaf15, #ffa600"
/>
```

The Lokasi Kejadian chart is empty, as there are no values for any Peristiwa entity for that property.

**Comment by petkong** [comment]
Dear Rafa,

Thank you Rafa for your best support. I still explore more with our teams related to the visualization data to be displayed.

Best regards,

Andri

**Comment by petkong** [comment]
Dear Rafa,

I'm trying to generate Per province (State) data from template **Peristiwa** ---> **Lokasi Kejadian**. Where the Barchart view will be replaced with the Geolocation View on the following page:

https://kebebasanberkesenian.uwazi.io/in/page/xg4sy5ol29/geolocation

Can you help me to display data visualization code related to Uwazi platforms visualization templates.

Regards,

Andri

ps : Testing Code

### Geolocation Coding Tes

<Dataset geolocation="true" />

<Map />

<Dataset url="/library/?q=(_types:!(%275bfbb1a0471dd0fc16ada146%27,%275d2d9f4622220717a93dbfcd%27),limit:0,order:desc,sort:creationDate,types:!(%275bfbb1a0471dd0fc16ada146%27,%275d2d9f4622220717a93dbfcd%27))" geolocation="true" />

<Map />

<Query name="entities" url="search?limit=10&order=desc&sort=creationDate"/>
<Value path="entities.rows.0.title"/>

<Query name="entities" url="search?limit=10&order=desc&sort=creationDate"/>

<ul>
<Repeat path="entities.rows">
     <li><Value path="title"/></li>
</Repeat>
</ul>

<Query name="entities" url="search?limit=10&order=desc&sort=creationDate"/>

<ul>
<Repeat path="entities.rows">
    <li>
         <EntityLink><Value path="title"/></EntityLink>
    </li>
</Repeat>
</ul>

<Value propkey="entity"><EntityLink>Some text</EntityLink></Value>

</div>

**Comment by petkong** [comment]
<Dataset geolocation="true" />

<Map />

<Dataset url="/library/?q=(_types:!(%275bfbb1a0471dd0fc16ada146%27,%275d2d9f4622220717a93dbfcd%27),limit:0,order:desc,sort:creationDate,types:!(%275bfbb1a0471dd0fc16ada146%27,%275d2d9f4622220717a93dbfcd%27))" geolocation="true" />

<Map />

<Query name="entities" url="search?limit=10&order=desc&sort=creationDate"/>
<Value path="entities.rows.0.title"/>

<Query name="entities" url="search?limit=10&order=desc&sort=creationDate"/>

<ul>
<Repeat path="entities.rows">
     <li><Value path="title"/></li>
</Repeat>
</ul>

<Query name="entities" url="search?limit=10&order=desc&sort=creationDate"/>

<ul>
<Repeat path="entities.rows">
    <li>
         <EntityLink><Value path="title"/></EntityLink>
    </li>
</Repeat>
</ul>

<Value propkey="entity"><EntityLink>Some text</EntityLink></Value>

</div>

**Comment by RafaPolit** [comment]
Hello Andri,

I'm not sure what do you require?  Do you want to show an actual map? Is this still about line / bar charts?  Can you please describe with more detail what you need?

Thanks,
Rafa

cc. @natasha-todi
