### ISSUE TITLE
Edit an entity with relationship metadata causes the addition of relations in the relationship hub

### ISSUE THREAD

**Issue by Chamrid** [huridocs/uwazidocs#5645]
- Have templates A and B.
- Create a relationship type relType1.
- Add to A a relationship property that points to template B using the type relType1.
- Create an entity B1 of type B
- Create an entity A1 of type A and assign B1 in the relationship field and save.
- Edit entity A1, do not make any changes and save.

Current behavior
A new relation between A1 and B1 is automatically added each time A1 is edited. No need to perform any change to A1. The simple fact to click on edit then save leads to the addition of one relation in the relationship hub.

Please see below a screencast illustrating the issue: 

https://user-images.githubusercontent.com/82155887/228432368-e71831c8-8d74-44c3-8bc6-2127ddd755a2.mov

**Comment by fnocetti** [comment]
After research we found out that this issue was introduced in version [1.109.0](https://github.com/huridocs/uwazi/releases/tag/1.109.0) with the mongoose and mongo update applied in #5587 
It is related to a change introduced by the library that prevents strings to be casted into ObjectIds in certain queries which, in this case, prevents the application from detecting the existing connection correctly.

**Comment by pddocs** [comment]
Please note: this issue is also replicating in my case as well, exactly as @Chamrid has reported.
