### ISSUE TITLE
New Settings/Collection UI

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazidocs#5826]

**Comment by juanmnl** [comment]
**Settings > Collection** is pretty similar to settings > account, in shape, just longer.
I'm sure, at some point, we are going to use a tab system on top to breakdown the categories, but for now, just a long scroll.

<img width="1440" alt="Screenshot 2023-05-17 at 19 21 39" src="https://github.com/huridocs/uwazi/assets/699945/57cce5be-d132-427a-a486-89f90fe29c36">

**Full section**

_*Disable inputs for properties that are not "enabled/activated"_

<img width="1190" alt="collection" src="https://github.com/huridocs/uwazi/assets/699945/86fc36c7-c3d8-471c-bdd1-14c95ad482cd">


[Prototype](https://www.figma.com/proto/HZX8qH0Aw8WiSch3Axczrn/new-comps?page-id=14%3A10151&node-id=377-13811&viewport=144%2C5643%2C0.68&scaling=min-zoom&starting-point-node-id=16%3A11467)

**Comment by RafaPolit** [comment]
Since we know that the contact email is affecting reset password mails and other emails, lets move the email outside the "Receiving email" from the form options.

Also, ensure that the placeholders are not "Domain or URL" for things that are not URLs

Non of us have any idea what the "Email status" is inside the Analytics section? cc @juanmnl

**Comment by juanmnl** [comment]
@RafaPolit Sorry about that, I guess it was a leftover from when I took the screenshots, as it's not on the prototype.

Update full collection screen:
<img width="1190" alt="collection" src="https://github.com/huridocs/uwazi/assets/699945/42c8cb75-47a5-4a2a-9f34-c5053175fe4a">

**Comment by RafaPolit** [comment]
Please check labels, some are suffering from copy-paste syndrome: there are two Default View labels, one of them is Date Format, or something like that.  So make sure the labels are correct.

**Comment by Zasa-san** [comment]
We could take the opportunity to address this since we are changing the UI -> #2032

**Comment by juanmnl** [comment]
Updated design:

<img width="1190" alt="collection" src="https://github.com/huridocs/uwazi/assets/699945/df67766c-ca58-4ab7-8886-7aaf1d559c50">

**Comment by Zasa-san** [comment]
After checking https://github.com/huridocs/uwazi/pull/6329 I've noticed that the tooltip for custom landing page doesn't represent how you would configure a library view correctly. 
It says
```
A page: /page/dicxg0oagy3xgr7ixef80k9
A filtered view in Uwazi: /library/?searchTerm=test
An entity: /entity/9htbkgpkyy7j5rk9
A document: /document/4y9i99fadjp833di
``` 
But the filtered view is just done by copy pasting the url from the library like: `/library/?q=etc...`


Could we update that tooltip to just reflect that (and check the others since we are at it) ?
