### ISSUE TITLE
New Settings/Pages UI

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazidocs#5827]

**Comment by juanmnl** [comment]
**Check updated comments at the bottom**


For **Settings > Pages** we're going to use a straight-up table for the pages list but adding the url of the page, and a boolean yes/no if the page is enabled as entity view page.

<img width="1440" alt="Screenshot 2023-05-17 at 19 29 40" src="https://github.com/huridocs/uwazi/assets/699945/3b5d2fbf-65c1-4939-8aa1-7e6e174fc40b">

**Comment by juanmnl** [comment]
It would be awesome, if possible, to try and add some sort of syntax highlighting on the code editor. 🥹

**Comment by juanmnl** [comment]
**Update:** Instead of opening the pages options through the side drawer, the user will navigate to the page's options to edit its content and "save/go back/cancel" to return to the full list of available pages.

There's a new "Save & Preview" action, that will save the current state of changes and open a new browser tab with the page and its _new_ content.

**Basic**
The "view page" action, only available on edit of an existing page, will open the page on a new browser tab.
<img width="1440" alt="Screenshot 2023-07-03 at 19 17 09" src="https://github.com/huridocs/uwazi/assets/699945/163aa30e-bde0-453f-a525-087cc391344a">

**Code**
<img width="1440" alt="Screenshot 2023-07-03 at 19 17 25" src="https://github.com/huridocs/uwazi/assets/699945/ea52c4c5-df84-4199-aeec-6f323b49018a">

**Advanced**
<img width="1440" alt="Screenshot 2023-07-03 at 19 17 38" src="https://github.com/huridocs/uwazi/assets/699945/e735d4ba-481a-43cd-a44a-7b2bbe02ad92">

**Comment by RafaPolit** [comment]
We were wondering if the "yes" "no" pills, and the "enable" button are not more visually legible and also less ambiguous (in the case of the enable) with the "toggle button" in iOS style?

Particularly the "Enable" button is, for me, very counterintuitive.  What happens when I click?  It colors to blue and reads "Enabled"?  Or it reads "Disable" as now clicking on it would disable it? So, is the text the action you perform when clicking? Therefore "unselecting" would have a different text?  I believe the "draggable pill" that shows enabled or not is much easier to read.

cc @juanmnl

**Comment by juanmnl** [comment]
@RafaPolit Here's the proposed interaction for the buttons. The pros that we talked about in the past, on having this interaction with a button instead of a toggle, was the ability for us to explicitly name the action in a pretty visible way (activate, enable, process, etc, which is an interaction we already use with OCR, information extraction, enable/disable properties on settings/collection, and more). Nevertheless I agree that it can still be managed with a toggle –and even a checkbox–. If we decide to do so, we should also define when to use which one and where.

![activate](https://github.com/huridocs/uwazi/assets/699945/a4f3a94e-227c-47fd-97ac-a948e5319d58)
![activated:disable](https://github.com/huridocs/uwazi/assets/699945/d73d5e17-6cb3-4f90-9cbc-808ed94bdc79)
