### ISSUE TITLE
Update README (production) to include --no-experimental-fetch

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#6068]
It is required to launch Uwazi with `--no-experimental-fetch` flag until we fix the implementation.  The README instructions need to reflect this.

**Comment by RafaPolit** [comment]
Is this still required with NodeJS 20? cc @daneryl

**Comment by daneryl** [comment]
Probably yes, needs to be double checked, fetch is still experimental in node 20.
fetch is stable in node 21, we probably need to fix whatever the problem is with node fetch and uwazi if we want to upgrade, unless the stable one is exactly the same functionality as the one we use now [node-fetch](https://github.com/node-fetch/node-fetch)

Do we have an issue with what is wrong with node fetch and uwazi?

**Comment by aphilop** [comment]
@RafaPolit @daneryl 
Is this still a critical bug? 
If yes, we have to deal with this somehow.
