### ISSUE TITLE
Custom landing page to library breaks uwazi

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazidocs#6250]
**Describe the bug**
Configuring a custom landing page to a library view results in error when loading uwazi.

**To Reproduce**
1. Create a blank state uwazi
2. Go to settings -> collection
3. Select "Use custom landing page" and add one of the following landing pages (im including more than one because the errors are different, not sure if this is the same issue or a different one)
  - "/en/library/?q=(allAggregations:!t,includeUnpublished:!t,order:desc,sort:creationDate,treatAs:number,unpublished:!f)"
  - "/en/library/"
4. Go to localhost:3000
5. See errors

**Expected behavior**
Library as a landing page should work properly, or maybe have a fallback in case of errors ? so that we can navigate to settings and fix the potential typo/error.

**Additional context**
On the first case "/en/library/?q=(allAggregations:!t,includeUnpublished:!t,order:desc,sort:creationDate,treatAs:number,unpublished:!f)" you can manually go to /settings deactivate the custom landing page and fix the instance.

Only on the second case "/en/library/" the error happens no matter what url you visit (this seems strange, im assuming the landing page code should only be executed when navigating to root ?)

**Comment by Zasa-san** [comment]
The error for the `/en/library/` case is happening in `app/react/getIndexElement.tsx` at `getCustomLibraryPage` function trying to substring `undefined`. It's an easy fix that could be done separately since it might break an instance entirely.

**Comment by RafaPolit** [comment]
@Zasa-san can you please create an issue with what is missing and if it's only that we can close this one or comment on what is missing? Thanks.

**Comment by Zasa-san** [comment]
The problem with the `/library/` landing page (regardless of it having the language set or not) is that we take it as a valid custom landing page. The same will happen if you set `/library/map/` as a custom landing page.
They are valid landing pages, but it breaks a single line of code in

https://github.com/huridocs/uwazi/blob/a718f2e31d447e8e55759b8c8096b16d10b715b7/app/react/getIndexElement.tsx#L13-L14
The issue here is that I will prevent the user from reaching the settings screen as well by manually navigating to `https://{host}/settings`, so they won't be able to correct the error themselves.
That can be quickly fixed in one line, by making the `query` constant optional when trying to substring it.
 
This still leaves the second problem, which is that our app may fail to parse a custom home landing page. In this second case I think that what should happen is that the user is redirected to the default library page, so they can easily access the settings screen and fix the problem.

**Comment by grafitto** [comment]
After my investigation, the first error is easy to fix, the second error is because when redirecting to the custom page specified, some part of the url is discarded.
For example if you set custom page to: `/en/library/?q=(allAggregations:!t,includeUnpublished:!t,order:desc,sort:creationDate,treatAs:number,unpublished:!f)`
It actually redirects to: `?q=(allAggregations:!t,includeUnpublished:!t,order:desc,sort:creationDate,treatAs:number,unpublished:!f)`
Completely disarding the `/en/library/` part of the url.
