### ISSUE TITLE
The Menu Language is always in English although we change it to another language (Arabic in our case ) 

### ISSUE THREAD

**Issue by Dawlaty** [huridocs/uwazidocs#6278]
![menu in arbic](https://github.com/huridocs/uwazi/assets/151935426/c229cb11-b439-420e-b3e9-5e1a2514058f)
![menu in English ](https://github.com/huridocs/uwazi/assets/151935426/fba95855-8d28-4fb9-a0c0-647c027f4102)

**Comment by mennaelmassry** [comment]
Thank you for reporting the issue @Dawlaty . We confirm that your issue is fixed and the menu bar is available in both Arabic and English.  

The translations are working well in Uwazi, that is whether through:
-  settings -> translations or 
- live translations  

Please do not hesitate to reach-out if you find any other issues..
