### ISSUE TITLE
Maps does not appear

### ISSUE THREAD

**Issue by Novry** [huridocs/uwazidocs#6427]
Hello, I'm trying to display maps following the tutorial here https://uwazi.readthedocs.io/en/latest/admin-docs/analysing-and-visualising-your-collection.html, but still can't display the maps, here are the details

my code
![image](https://github.com/huridocs/uwazi/assets/35475908/0380bf88-647e-4133-849b-7cd411c5bd7d)

result
![image](https://github.com/huridocs/uwazi/assets/35475908/a22a991b-b57d-478b-a033-5e6cadb76b24)

To be honest, I'm having a hard time knowing which URL I need to copy, I tried making it on the Uwazi demo website page here: https://demo.uwazi.io/
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by RafaPolit** [comment]
The Map is a tricky element.  The automatically generated ```class="Map"``` element needs a set height, as it doesn't expand automatically based on its content, as it doesn't have the ability to determine how tall it should be.

If you try this code:
```
<style>
.Map {
  height: 400px;
}
</style>
<Dataset geolocation="true" />
<div>Map should be showing</div>
<Map />
```

It should provide a minimum working example that actually shows the map.

If this works, we can look into refining the URL, but it kind of looks like you have the right type of URL that the Dataset element is expecting.

**Comment by Novry** [comment]
Hi @RafaPolit thanks for reply

I see, Your advice really works, I really appreciate it.
But, currently the following notification appears when I click on one of the numbers on the maps
![image](https://github.com/huridocs/uwazi/assets/35475908/232ac971-32cb-415b-ad7a-407533d991c0)

my code
![image](https://github.com/huridocs/uwazi/assets/35475908/bc5e1704-1450-46d9-a85e-fbf745252300)

**Comment by RafaPolit** [comment]
Glad it worked.

We see this issue sometimes when reloading pages, but it shouldn’t happen upon clicking on the map.  

Are you running on a production build of Uwazi? How are you starting the service?

Another possibility is: Do you have the mapbox key configured in your settings?

**Comment by Novry** [comment]
My Uwazi website is here https://tapol.uwazi.io/, I haven't published all the data yet, so currently I'm working on the demo website https://demo.uwazi.io/ to try to change the appearance of the page etc.

do you mean this mapbox?
![image](https://github.com/huridocs/uwazi/assets/35475908/50da6532-d70a-4ef9-9e25-1b0d3f04491d)

It seems like I didn't change any settings, apart from creating a page.

**Comment by RafaPolit** [comment]
Ok, I understand a bit better the context.

Since you are hosting with us, all my questions about running production builds are not relevant.  This is only for self-hosted collections.  If you are hosting with us, you have the latest production build always.

If these errors are coming from the Demo version, then I also understand a bit better the problem.  Demo is used by any user that wants to toy around with the platform, and it is good for a few quick tests, but anything longer than that and you risk submitting something the moment the service is restarting and zeroing out its values, and you end up with inconsistent data.

For anything remotely reliable, please, use your own collection so that we can help support with pages that persist over time (Demo pages are reset every few hours).

Once you have some implementations on your own data (even if it is not yet shared with the public) we can look into providing support and help to get you flowing smoother.

**Comment by RafaPolit** [comment]
I am closing this issue, if you have any further concerns, don't hesitate to open a new one.,
