### ISSUE TITLE
how to make interactive maps

### ISSUE THREAD

**Issue by Novry** [huridocs/uwazidocs#6439]
Hi There, how to make maps like this: https://nkpd.io/en/page/bdkqwxwh7ar/penal-facilities
![image](https://github.com/huridocs/uwazi/assets/35475908/3ba7d713-bcc4-4e95-83c8-a69595ef1301)

I'm not sure, but this seems to be a feature of Interactive Maps.

Thank you

**Comment by RafaPolit** [comment]
These are custom design pages with SVG graphs and the interaction is done by customizing the JavaScript within the Page in order to provide the interactivity.

You have already delved into the documentation, and you may see mention to certain "off the shelf" components we provide, that know how to interact with our data in order to help page designers to get started with some basic elements: BarChart, PieChart, Map, Counter... these are a few pre-made components that you can use to  embellish the look of your pages.

If you need these type of additional interactions and look, then you most likely will not be able to rely on default components, but rather on custom page design.  Let me reach out to your PO and get them in contact with you so that we can look into your needs more closely.

**Comment by RafaPolit** [comment]
I'm closing this issue for now. If you have any further questions, don't hesitate to contact us.
