### ISSUE TITLE
Settings Filter new UI

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazidocs#6585]
```[tasklist]
### Tasks
```

**Comment by juanmnl** [comment]
Mostly the same patterns we have everywhere else by now.

**Filters table:**
<img width="1192" alt="Screenshot 2024-03-11 at 19 06 50" src="https://github.com/huridocs/uwazi/assets/699945/c60be7e4-94b2-4c46-b335-80aad6a96f30">

**Expanded group:**
<img width="1192" alt="Screenshot 2024-03-11 at 19 06 31" src="https://github.com/huridocs/uwazi/assets/699945/92919131-2825-4c1c-b4f8-25e27414a4cb">

---

**Add entity type:**
(it looks decentered because it's a screenshot of the table-only and it's missing the settings navigation side-panel in the context)
<img width="1192" alt="Screenshot 2024-03-11 at 19 07 17" src="https://github.com/huridocs/uwazi/assets/699945/28615dac-deb3-4fa0-b25e-cae85dd77238">

**Add group w/ entities dropdown:**
<img width="1440" alt="Screenshot 2024-03-12 at 10 51 31" src="https://github.com/huridocs/uwazi/assets/699945/f9739130-ec31-4e9a-8716-4b0a5a4f1b74">

**[Prototype](https://www.figma.com/proto/HZX8qH0Aw8WiSch3Axczrn/new-comps?page-id=14%3A10151&type=design&node-id=605-16285&viewport=-6242%2C4506%2C0.55&t=EzbCDIVOUMYpDgDt-1&scaling=min-zoom&starting-point-node-id=3207%3A48780&mode=design)**
