### ISSUE TITLE
Search by Property

### ISSUE THREAD

**Issue by djhmateer** [huridocs/uwazidocs#6601]
Hi

Is there a way to search by a template's text `Property` eg CASE_ID - TEST500 in screenshot below.

![image](https://github.com/huridocs/uwazi/assets/111231/cdafa4ea-d348-4767-b681-e8177330173e)

This search gives me more than I wish ie I don't want the asdf CASE

[https://github.com/huridocs/python_uwazi_API](https://github.com/huridocs/python_uwazi_API) I'm using this API wrapper if I need to access the database in a lower level to perform a query?

**Comment by RafaPolit** [comment]
This is an interesting scenario, we have had some use cases where users need to do this.  We developed a Search V2 API endpoint which is, indeed, capable of what you need.   This may get a little technical, so please feel free to follow up with any questions.

In order to find text by a particular property, you would need to first make sure that that is the actual property name defined in the template, and not a translation that is recorded as CASE_ID.  If that is indeed the case, you need to pass the following filter object to the search v2 query:
```
{filter: {'metadata.CASE_ID': '"TEST500"'}}
```

This will filter entities whose CASE_ID (and not other properties) contain exactly that value.  In order to pass that object to a GET query to the API, there are several methods.  The API wrapper may work if you already have it running.  You can URL encode the query using SUPERTEST if you are using NodeJS (and can extrapolate the needs from the search v2 examples found here: https://github.com/huridocs/uwazi/blob/development/app/api/search.v2/specs/filters.spec.ts), or any other request-making platform you prefer (POSTMAN has an online service that could be used for quick testing purposes, for example).

I'm going to list here the URL encoded query that should yield your expected results:
```
https://hmsoftware.uwazi.io/api/v2/search?filter%5Bmetadata.case_id%5D="TEST500"
```

If you URL decode this, you will see a more "readable" format of what we are requesting from the API (DO NOT use the below link as a request, the above link has the encoding needed for the backend to understand the object structure that is required):
```
https://hmsoftware.uwazi.io/api/v2/search?filter[metadata.case_id]="TEST500"
```

This should work as you expect.  In your case, you have the added complexity that, since your collection is private, you need to first acquire the login credentials and send them via cookie with the query in order to fetch the expected results.

All the API search endpoints query the Elastic Search indexes, and not directly the database, so they are not yet a "lower level" query, but hopefully this will suffice for your needs?

Please let us know if you have any further doubts or if the above method is not working as expected.  Best regards,
Rafa.

ps.  In your particular case, the Quotes (") around the term `TEST500` may not be needed, since it is a single word without any spaces.  So, if you know for sure there will be no spaces required, it could be a safer bet to remove those quotes, as they are not URL encoded and, therefore, passed as actual quotes to the query, but may need to be escaped on the platform creating the request, so some trial and error may be required.

**Comment by djhmateer** [comment]
Thank you very much @RafaPolit this is great.

Added a new function to my wrapper and got it working as expected:

```py
def get_shared_ids_search_v2_by_case_id(self, to_process_template: str, case_id: str):

 # this works but is querying all templates eg CASES and if Content had a case_id it would query this too.
 # url_and_query = f'{self.uwazi_request.url}/api/v2/search?filter[metadata.case_id]="{case_id}"'

 # filter on the correct template too
 url_and_query = f'{self.uwazi_request.url}/api/v2/search?filter[metadata.case_id]="{case_id}"&filter[template]={to_process_template}'

 response = self.uwazi_request.request_adapter.get(url_and_query,
                                                   headers=self.uwazi_request.headers,
                                                   cookies={'connect.sid': self.uwazi_request.connect_sid,
                                                            'locale': 'en'})
 if response.status_code != 200:
     raise InterruptedError(f'Error getting entities to update')

 return [json_entity['sharedId'] for json_entity in json.loads(response.text)['data']]
```

Found the sorting specs very useful too in getting the template filtering working:

https://github.com/huridocs/uwazi/blob/development/app/api/search.v2/specs/sorting.spec.ts#L126
