### ISSUE TITLE
Activity log date selection generates requests even without change any date

### ISSUE THREAD

**Issue by mfacar** [huridocs/uwazidocs#6665]
**Describe the bug**
When clicking into date from or date to, the component fires a search even without selecting any date

**To Reproduce**
1. Go to Settings/Activity Log
2. Click on the field From
3. See how the page makes a request

**Expected behavior**
Clicking on the `from` or `to` fields only fires a search when a change in the range is made

**Comment by serena-huridocs** [comment]
@mfacar I am sharing this note on behalf of this week's testing group: maybe, what's captured in this screencast, is not considered "flickering" or it is an expected behavior but when a user sets dates in the **From** and **To** fields, the screen blinks while loading a result. 

Uploading 6665 issue.mov…
