### ISSUE TITLE
[IX] Fix or sanitize the response to be consistently arrays (or deal with single values)

### ISSUE THREAD

**Issue by konzz** [huridocs/uwazidocs#6798]
We observed this issue while testing the changes. For two different extractors, both pointing to a `select` property the `currentValue` and the `suggestedValue` came some times as a plain string `"value"` and some times as an array `["value"]`.
Not clear how to reproduce this bug yet, @gabriel-piles might provide more context.

**Comment by LaszloKecskes** [comment]
While we were not able to reproduce the issue, after reviewing the code we found that the messages from the service were very lazily validated, and potentially something like this could slip through the cracks. It is unclear whether this was the case when the issue occurred, since this would assume a disagreement between the service and Uwazi.

The linked pull request will not be a fix, but will implement validation that will hopefully catch any unnoticed mismatches in the suggestion messages interfaces, that might cause problems.
