### ISSUE TITLE
[IX] Support relationship properties

### ISSUE THREAD

**Issue by aphilop** [huridocs/uwazidocs#6800]
The functionality must be extended to support also relationship properties.
The relevant information about what is supported in the "Create Extractor" modal dialog must also be updated accordingly. 

Set a hard limit for 500.

<img width="596" alt="image" src="https://github.com/huridocs/uwazi/assets/102693686/f054bce5-5935-4422-b0be-d0c303b7906c">

**Comment by aphilop** [comment]
@konzz I added the constraint about the hard limit we discussed. You might want to add some context to this to make it more clear (?)

**Comment by txau** [comment]
Since the relationship fields can eventually point to a vast amount of entities depending on how they are configured, we decided to set a hard limit to the first 500 to avoid having an unmanageable select field. This is not the ideal solution but it is going to probably fit all the use cases we are currently handling.

**Comment by LaszloKecskes** [comment]
Changed the title to better represent the content of the issue. The development is not only about the creation of the extractor, but to support relationship properties through the entire IX cycle. Namely:
- extractors (creation, update, etc.)
- model training
- getting and saving suggestions
- accepting suggestions
