### ISSUE TITLE
Filter settings [Drag and drop]: When all items dragged out from the group, the group becomes a new filter item

### ISSUE THREAD

**Issue by serena-huridocs** [huridocs/uwazidocs#6820]
**Describe the bug**
When a user extracts all the items from the group in the filter settings, the group becomes a filter. It seems to be a bug because we use entity types (templates) for the creation of primary filters; labels that we use for grouping should not become filters. As a result, when a former group name is displayed on the filters panel, it always shows 0 entities, because there is no template associated with it. 

**To Reproduce**
1. Go to Settings and navigate to Filters from the left menu
2. Add group and add entity types to the group
3. Save the change
4. Drag all the entity types belonging to the group outside of the group
5. See that the group is displayed as a filter item as a result

**Screenshots**

![Screenshot 2024-05-24 at 15 35 25](https://github.com/huridocs/uwazi/assets/100300126/441367c5-c9b4-4737-9396-5c4a04ceb980)

**Filter testing** was a group before. It turned into a filter item after we extracted all the items from it. 

**Device (please select all that apply)**
 - [X] Desktop
 - [ ] Mobile

**Browser**
Chrome

**Additional context**
The issue was discovered during the testing of the fix [#6782](https://github.com/huridocs/uwazi/pull/6782)[#6782](https://github.com/huridocs/uwazi/pull/6782) by the testing group 3 (@oleksandrako @pddocs).

**Comment by aphilop** [comment]
@serena-huridocs @oleksandrako @pddocs Thanks for reporting this!
I can see in the filters the entry **Filter testing** that indicates that something went wrong.
Unfortunately, I cannot reproduce this bug with the provided steps. I can create a group, add entities and save it, and then when I remove all items from the group, the group is automatically deleted.
1. When was this tested?
2. Might be there are additional steps/conditions, which led to the behavior you observed, that I am missing in order to reproduce the bug?

**Comment by aphilop** [comment]
After discussing with @serena-huridocs, the bug still persists. The description would be updated to make clearer the steps to reproduce.

**Comment by aphilop** [comment]
Will be handled with #7052
