### ISSUE TITLE
Login + blank password + hitting enter bricks the instance for that particular user

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#6860]
Attempting to login into Uwazi with a blank password AND hitting the enter key (not hitting the login button with the mouse) will brick the instance for that particular user due to something related with the cookie. It will display this error:

![image](https://github.com/huridocs/uwazi/assets/489831/0821e8ab-14a0-4c5d-a1a4-51f83e6bb1ef)

And attempting to reload the instance will show how it is bricked.

![image](https://github.com/huridocs/uwazi/assets/489831/19b30af0-d0e7-41a0-adc0-4be27570107a)

Clearing the cookies for this instance will resolve the problem.

**Comment by konzz** [comment]
The issue is that the backend is "successfully" logging in with an empty password, and by that I mean it returns a `200`.

![Screenshot 2024-06-05 175145](https://github.com/huridocs/uwazi/assets/948117/c19cad33-c632-4b38-b477-2c3b344b4a91)
![Screenshot 2024-06-05 175152](https://github.com/huridocs/uwazi/assets/948117/3c0e5b80-08b4-4d96-a31f-668c13b58752)

The login process returns a `false` but not an error so after that, passport (the auth library) serializes a non-existing user, and every subsequently request goes through passport again to recover the user here:
https://github.com/huridocs/uwazi/blob/fcd81957f2a2f34367ceb01ec7651144f01b3e1c/app/api/auth/passport_conf.js#L29-L41

This calls `users.getById` with an `undefined` id, and that's when Mongo throws the error because `undefined` is not a valid `ObjectId`

I think the critical solution should be not to allow login with those credentials.
