### ISSUE TITLE
[AT] II. Storing translations

### ISSUE THREAD

**Issue by LaszloKecskes** [huridocs/uwazidocs#6951]
This issue is about the database/entity side of the translation storing process. Fetching the results from the service are handled in a different issue. Validations will be the responsibility of the worker process. 

The saving process should:
 - store the translation in the metadata
 - append a `machine_translated` flag in the metadata (edit: we are not appending a flag but a regular text as part of the value).

Make sure that:
 - the entity flows (get, save, etc.) leave this flag intact (edit: I think this is not needed since there is no flag but rather appending the text in the value, if the user edits it it is ok to remove this data)
 - denormalization works and carries this information over (edit: this should be already denormalized as part of Uwazi's regular denormalization).

**Comment by aphilop** [comment]
@LaszloKecskes 
In the last product call, we made the decision to use a textual disclaimer (“AI translated”) that should be displayed in the translated property and could be removed manually by the users when editing the property. 
Is this the correct issue to document this so that it is considered during development?

<img width="503" alt="image" src="https://github.com/huridocs/uwazi/assets/102693686/70fc6975-aa10-4c1c-881b-8c497d4a09c2">

<img width="499" alt="image" src="https://github.com/huridocs/uwazi/assets/102693686/39dbd144-71cb-4aec-8892-504a2c0dfcd3">

**Comment by LaszloKecskes** [comment]
> @LaszloKecskes In the last product call, we made the decision to use a textual disclaimer (“AI translated”) that should be displayed in the translated property and could be removed manually by the users when editing the property. Is this the correct issue to document this so that it is considered during development?

For the display, there are no front end issues yet. The backend issue about the flag removal is #6956
