### ISSUE TITLE
Files health check should not account for url attachments

### ISSUE THREAD

**Issue by fnocetti** [huridocs/uwazidocs#6992]
The files health check script is counting attachments that are not stored files but urls as missing in storage, while they are by definition not put in the storage.

**Comment by aphilop** [comment]
@txau @RafaPolit 
What is the importance/severity of this in order to judge about its priority?

**Comment by txau** [comment]
I think this should by an easy fix. @fnocetti and @varovaro have a better knowledge of the insides, but my take is that a quick check with a regexp to tell the URLs from the files apart would fix this so the results of the health check are more accurate.

If that is so, I would put it as high in order to:
- have a proper health check
- wrap up this whole functionality now that we are at it

**Comment by fnocetti** [comment]
This is definitively an easy fix. I will leave a PR ready before today EOD

**Comment by daneryl** [comment]
I have reviewed and tested @fnocetti PR LGTM, merged and deployed.
