### ISSUE TITLE
Download file with original name

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#7109]
We store the original file name, but we discard it upon download, offering the internal filename instead. This removes a semantic file naming.

related: https://github.com/huridocs/uwazi/issues/3132

**Comment by Joao-vi** [comment]
I just checked locally, using production branch and was not able to reproduce the issue.

The current behavior is: the link for download have the File ID in order to identify and download on S3, once the File is downloaded on client, we have the original File name set as default when saving of the user's computer.

Link for download:
![Image](https://github.com/user-attachments/assets/821888f6-206f-465c-999f-4a3de106c9e8)

Original filename: 
![Image](https://github.com/user-attachments/assets/6350f0bc-e737-4a1a-8e44-b5e94bd0b671)

@txau

**Comment by txau** [comment]
Ok. I guess the link was misleading. Closing then
