### ISSUE TITLE
[IX] The extractor where it lists DOCUMENT, it uses the ENTITY title and not the DOCUMENT title

### ISSUE THREAD

**Issue by RafaPolit** [huridocs/uwazidocs#7141]
### The extractor where it lists DOCUMENT, it uses the ENTITY title and not the DOCUMENT title

The extractor information, under the column DOCUMENT does not use the document name but the entity's name.  When having more than one document per entity, this gets very confusing.  Maybe it's just the column name that is wrong? Or the concept of which value is being used to populate it.

**Comment by txau** [comment]
This may be a product of iterations in the design. The language use to be a column and we decided to remove it, that was disambiguating the repetition of titles. Also in previous versions we used to have the document title instead of the entity title but we realized most document titles are bad, non-descriptive at all, so we resorted to the entity title.

This could be fixed by adding an extra set of filters for filtering by language, but we can live without this for now.

I guess we can close this issue and leave things as they are.

**Comment by RafaPolit** [comment]
No, I don't agree.  This is very, very confusing. You have a column named DOCUMENT.  And the values underneath are Entity Titles.  I do agree that document names can be non-descriptive, but we can solve this. For example:
DOCUMENT FOR:
Entity Name (language) 

We don't put an extra column, but we differentiate that what we are seeing is an entity name, not a document, and we can append the language initials to the entity title of the document's language.

**Comment by txau** [comment]
We can perform that change, but keep in mind that since we should have a document per language, the title is going to be in that language.
