### ISSUE TITLE
[IX] - Feedback when missing segmentations

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#7147]
When one or more segmentations are missing, the IX reports it to the user as following:

![image](https://github.com/user-attachments/assets/bb69fad0-b398-4ed8-b898-c4d783c5e1e4)

This leaves the user in a state of confusion since they try to label data and it does not fix the issue. It would be advisable to change the feedback message to:

"Some documents are not segmented yet, please try again later"

**Comment by RafaPolit** [comment]
Indeed, "No labeled data" is return on a whole sequence of different checks, so there could be labeled data but not files found, etc.  So a much better flow and error reporting is needed.

**Comment by daneryl** [comment]
This kind of errors only happen when none of the documents are segmented and labeled.

"No labeled data" only happens when 0 documents are labeled

No files segmented only happens when 0 documents are segmented

This is properly reported now but the message will show "There are no documents segmented yet, please try again later"

**Comment by daneryl** [comment]
#7531 fix does not work well for selects/multiselects/relationships, reopening...

**Comment by daneryl** [comment]
> [#7531](https://github.com/huridocs/uwazi/pull/7531) fix does not work well for selects/multiselects/relationships, reopening...

fixed
