### ISSUE TITLE
Odd behavior with menu translations

### ISSUE THREAD

**Issue by Zasa-san** [huridocs/uwazidocs#7175]
Menu items can be missing in translations collection (only checked the UI, need to confirm what happens in the DB) under some conditions.

- In a collection with at least two languages create a menu with only root items (no groups)
- Save
- Create a group and drag an existing item into the group
- Save again
- Check the system translations for `Menu`, the root item moved into the group is not present.

@txau detected a case where in the `Menu` collection you can find entries that are no longer present in the menu itself, this could be related to the issue described here.

**Comment by RafaPolit** [comment]
@Zasa-san can you confirm if this is happening ONLY for dragging existing items? Or this is happening for any child items in a group?

**Comment by Zasa-san** [comment]
> @Zasa-san can you confirm if this is happening ONLY for dragging existing items? Or this is happening for any child items in a group?

When creating a new group with a new item it works correctly. It seems it's existing items that are a problem when changing from root to children.

**Comment by konzz** [comment]
The problem in particular is that at the time of checking for deletions the backend does not take in to account subgroups.
- The issue described here happens because the `matchValue` is a find over newValues top values, and if a value has been moved to a group will not find it and will mark it for deletion.
- A similar issue is that if you delete an item inside of a group since the first step is processing the `currentValues` in a `forEach` it will only check for the deletion / updates of the top level entries, and the translation entry will remain after deleting it.

https://github.com/huridocs/uwazi/blob/ab33a3393994f9eb496b20ff1efea4cd805217f8/app/api/settings/settings.ts#L40-L47
