### ISSUE TITLE
Some documents do not have a language defined

### ISSUE THREAD

**Issue by txau** [huridocs/uwazidocs#7486]
**Describe the bug**
Direct inspection of the database tosses documents with null for the defined language for CEJIL. These documents have a table of contents and are not, non-OCRed or the language would be "Other".

**To Reproduce**
Run a query looking for null value for the language in the files collection.

**Expected behavior**
All documents should have a language or "Other" when unknown.

**Comment by RafaPolit** [comment]
@daneryl will create a script to assess the extent of the issue
@Joao-vi will then develop the fix

**Comment by Joao-vi** [comment]
Just checked the persistence workflow on files collection and there is a validation layer that prevents from saving a Files with value of null or undefined.

This validation layer is used behind files api, on app/api/files.ts.

I wonder if this bug still persist because I couldn't save a File with a value of null, check image bellow.
![Image](https://github.com/user-attachments/assets/f340fa53-1951-4935-81aa-3aeb82f798cc)

In case still persist, are we using a way to persist Files on mongodb that does not use this files api, and thefore does not pass through the validation layer ?  

![Image](https://github.com/user-attachments/assets/8b548587-cde5-47f7-a43a-229857fa84f3)

@txau @daneryl @RafaPolit

**Comment by txau** [comment]
This is probably an old bug. A good way of checking it would be running a query for these files on all DBs and get the creation and modification date for each file with no language.

We have several pathways on which files can be created or modified including direct upload, bulk upload, CSV import, sync, preserve,. OCR. I don't know if any of them does not rely on the files API.

**Comment by Joao-vi** [comment]
@txau Got it, going to check that.

For those files already saved with language as null, should we change all of its language from "null" to "other" ?

**Comment by txau** [comment]
@jowe should change it to their actual language. Normally that is automatically detected by franc, but we need to discuss how to address it. If we have the list of affected documents we can make better decisions, maybe it is a very small list and we can just fix it manually.

**Comment by daneryl** [comment]
@Joao-vi @txau  we have thousands of cases, will send some details to @Joao-vi

**Comment by daneryl** [comment]
> [@Joao-vi](https://github.com/Joao-vi) [@txau](https://github.com/txau) we have thousands of cases, will send some details to [@Joao-vi](https://github.com/Joao-vi)

After double checking, we have around 350 cases, all of them except 10 are files that failed the conversion, this is the reason they do not have language, the 10 missing are a mistery because at the time we did not even have creationDates.

i suggest we manually fix those and revisit this if it happens again.

> Expected behavior
All documents should have a language or "Other" when unknown.

I think this is a nice to have and not a high priority issue, low priority maybe medium.

**Comment by daneryl** [comment]
> i suggest we manually fix those and revisit this if it happens again.

Fixed.
