### ISSUE TITLE
Update elasticsearch from 7.17.6 to 7.17.25

### ISSUE THREAD

**Issue by gabriel-piles** [huridocs/uwazidocs#7508]
I could not start Elasticsearch version 7.17.6. 

The problem was resolved by using version 7.17.25.

And, it is happening to more people in the tech team.

**Comment by aphilop** [comment]
@RafaPolit to discuss this during the backend call and assess the impact and effort.

**Comment by txau** [comment]
Ideally we upgrade to the next major

**Comment by daneryl** [comment]
@txau @aphilop This is a local development issue,  some compatibility problem with the newest Linux kernel  and the openJDK version our elasticsearch docker image uses, i had updated my kernel recently and encountered this issue and confirmed with @gabriel-piles he also did, prepared a [PR](https://github.com/huridocs/uwazi/pull/7517) with the next minor version 7.16.7 that has an OpenJDK update and fixes the issue.
I think this can be closed since this is only the version of the docker-compose provided for local development, all uwazi tests are green.

In case we want to upgrade Elasticsearch we should create another issue for that, this needs back end/infra coordination and most likely we can not upgrade to the latest version directly, i took some minutes to test latest version locally 8.16.1 and we have 3 test suites failing, looks like from the back end perspective this is not a lot of work.

**Comment by txau** [comment]
@daneryl ok. It makes sense.

**Comment by aphilop** [comment]
OK, closing this.
